mod anagrams_in_a_string;
pub use anagrams_in_a_string::Solution as AnagramsInAString;

mod longest_substring_without_repeating_characters;
pub use longest_substring_without_repeating_characters::Solution as LongestSubstringWithoutRepeatingCharacters;

mod longest_repeating_character_replacement;
pub use longest_repeating_character_replacement::Solution as LongestRepeatingCharacterReplacement;

mod maximum_sum_of_distinct_subarrays_with_length_k;
pub use maximum_sum_of_distinct_subarrays_with_length_k::Solution as MaximumSumOfDistinctSubarraysWithLengthK;
